# Generated by Django 3.1.3 on 2021-05-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_devicelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='config',
            field=models.TextField(blank=True, verbose_name='Конфигурация устройства'),
        ),
    ]
